import './globals.css'
// import Image from "next/image";
// import bg_image from "../../public/cool-bgimage.jpg"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`{inter.className} bg-image h-screen w-screen`}>{children}</body>
    </html>
  )
}
